### ISSUE TITLE
NullPointerException on AerisMapView inside ViewPager

### ISSUE THREAD

**Issue by josemontiel** [aerisweather/AerisAndroidSDK#10]
> Exception java.lang.NullPointerException: Attempt to invoke virtual method 'void com.aerisweather.aeris.maps.AnimationController.pauseAnimations()' on a null object reference
> com.aerisweather.aeris.maps.AerisMapView.onPausePressed (AerisMapView.java:1394)
> com.aerisweather.aeris.maps.AerisMapView.onWindowVisibilityChanged (AerisMapView.java:1586)
> android.view.View.dispatchWindowVisibilityChanged (View.java:11077)
> android.view.ViewGroup.dispatchWindowVisibilityChanged (ViewGroup.java:1286)
> android.view.ViewGroup.dispatchWindowVisibilityChanged (ViewGroup.java:1290)
> android.view.ViewGroup.dispatchWindowVisibilityChanged (ViewGroup.java:1290)
> android.view.ViewGroup.dispatchWindowVisibilityChanged (ViewGroup.java:1290)
> android.view.ViewGroup.dispatchWindowVisibilityChanged (ViewGroup.java:1290)
> android.view.ViewGroup.dispatchWindowVisibilityChanged (ViewGroup.java:1290)
> android.view.ViewGroup.dispatchWindowVisibilityChanged (ViewGroup.java:1290)
> android.view.ViewGroup.dispatchWindowVisibilityChanged (ViewGroup.java:1290)
> android.view.ViewGroup.dispatchWindowVisibilityChanged (ViewGroup.java:1290

**Comment by sshie** [comment]
Hi Jose,

Thanks for the report - can you let us know what version of the SDK this occurred in?

**Comment by josemontiel** [comment]
Hello @sshie ,

My bad, this occurs on v2.3.0

**Comment by sshie** [comment]
Perfect, thanks!

**Comment by sshie** [comment]
Hi Jose,

Just a quick note to let you know that version 2.4.0 has been released, which should fix this issue. 

Thanks again!

**Comment by josemontiel** [comment]
Hello @sshie ,

I'm still seeing this crash happening after updating the SDK to 2.4.0

**Comment by sshie** [comment]
Thanks for the update Jose. I have added this back into the issue list for the next update.
